# Generated by Django 3.2.7 on 2021-09-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, unique=True)),
                ('last_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('summary', models.CharField(max_length=1000, unique=True)),
                ('cover', models.URLField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('number_pages', models.IntegerField(null=True)),
                ('format', models.CharField(max_length=100, unique=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='cessions.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, unique=True)),
                ('last_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Royalties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('royalties_percent', models.IntegerField(null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publishing_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('territories', models.ManyToManyField(blank=True, related_name='publishing_company', to='cessions.Territory')),
            ],
        ),
        migrations.CreateModel(
            name='Cession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration', models.IntegerField(null=True)),
                ('pdf_sent_at', models.DateTimeField()),
                ('contract_sent_at', models.DateTimeField()),
                ('contract_signed_at', models.DateTimeField()),
                ('bill_sent_at', models.DateTimeField()),
                ('book_sent_at', models.DateTimeField()),
                ('advance_price', models.IntegerField(null=True)),
                ('advance_price_paid_at', models.DateTimeField()),
                ('data_price', models.IntegerField(null=True)),
                ('data_price_paid_at', models.DateTimeField()),
                ('files_sent_at', models.DateTimeField()),
                ('model_received_at', models.DateTimeField()),
                ('language', models.CharField(max_length=200, unique=True)),
                ('occasion', models.CharField(max_length=200, unique=True)),
                ('comment', models.CharField(max_length=200, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cessions.agency')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cessions.book')),
                ('royalties', models.ManyToManyField(blank=True, related_name='cessions', to='cessions.Royalties')),
                ('territories', models.ManyToManyField(blank=True, related_name='cessions', to='cessions.Territory')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cessions.collection'),
        ),
        migrations.AddField(
            model_name='book',
            name='illustrators',
            field=models.ManyToManyField(blank=True, related_name='books', to='cessions.Illustrator'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cessions.publishing_company'),
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='books', to='cessions.Topic'),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, unique=True)),
                ('last_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cessions.agency')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='territories',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='cessions.Territory'),
        ),
    ]
