# Generated by Django 3.2.7 on 2021-09-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_company',
            name='territories',
            field=models.ManyToManyField(blank=True, related_name='publishing_companies', to='cessions.Territory'),
        ),
    ]
