# Generated by Django 3.2.7 on 2021-09-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0002_alter_publishing_company_territories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='country',
        ),
    ]
