# Generated by Django 3.2.7 on 2021-09-27 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0003_remove_agency_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='email',
        ),
        migrations.CreateModel(
            name='Publisher_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, unique=True)),
                ('last_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('publishing_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cessions.publishing_company')),
            ],
        ),
    ]
