# Generated by Django 3.2.7 on 2021-09-27 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0006_auto_20210928_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='publisher_contact',
            name='name',
        ),
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher_contact',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher_contact',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cession',
            name='comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cession',
            name='language',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cession',
            name='occasion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
