# Generated by Django 3.2.7 on 2021-10-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0009_alter_book_publishing_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cessions.collection'),
        ),
    ]
