# Generated by Django 3.2.7 on 2021-10-01 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0010_alter_book_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cession',
            name='publishing_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cessions.publishing_company'),
            preserve_default=False,
        ),
    ]
