# Generated by Django 3.2.7 on 2021-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0012_alter_cession_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cession',
            name='advance_price_paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='data_price_paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
