# Generated by Django 3.2.7 on 2021-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0013_auto_20211001_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cession',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
