# Generated by Django 3.2.7 on 2021-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0016_alter_cession_publishing_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
