# Generated by Django 3.2.7 on 2021-10-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0017_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
