# Generated by Django 3.2.7 on 2021-10-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0018_alter_book_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cession',
            name='bill_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='book_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='contract_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='contract_signed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='files_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='model_received_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='occasion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='pdf_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
