# Generated by Django 3.2.7 on 2021-10-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0019_auto_20211001_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cession',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cessions.agent'),
        ),
        migrations.AddField(
            model_name='cession',
            name='publisher_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cessions.publisher_contact'),
        ),
    ]
